---
title: "function"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r, message=FALSE}
library("stringdist")
library(tidyverse)
library(tuneR)
library(devtools)
library(ggplot2)
library(tsfeatures)
```

```{r}
waveSeq <- readWave("blinking-20210418T233857Z-001/blinking/blink_olli_bot_v1.wav")
waveSeq #shows the things we can retrieve from this class
slotNames(waveSeq) #idk what this is tbh: returns info about components (slots) for a given object --> class, use @ --> shows the s4 components


# time (in seconds) of the sequencing
timeSeq <- seq_len(length(waveSeq))/waveSeq@samp.rate 
#timeSeq


plot(timeSeq, waveSeq@left, type = "l", ylab="Signal", xlab="Time(seconds)")

```


```{r}
streaming_classifier = function(wave_file,i,  
                                window_size = wave_file[[i]]@samp.rate, 
                                increment = window_size/3, thresh=250000){

  #this getting x and y 
  Y = wave_file[[i]]@left # all data is stored here
  xtime = seq_len(length(wave_file[[i]]))/wave_file[[i]]@samp.rate #seq len
  plot(xtime, Y, type="l", lty=1,)
  
  #initializing variables
  predicted_labels = c() #stores predicted
  lower_interval = 1 #used to increment window 
  max_time = max(xtime)*window_size


  predicted=c()
  
  #initialing signal vector 
  signal=c()
  signal=append(signal, 0)
  sc=c()
  sc=append(sc,0)
  
  p=c()
  
  switch=FALSE
  
  #used to graph stuff
  var=c()
  cp=c()
  av=c()
  
  
  while(max_time > lower_interval + window_size)
  {
    upper_interval = lower_interval + window_size
    interval = Y[lower_interval:upper_interval] 
    xinterval=xtime[lower_interval:upper_interval]#gets corresponding time

  #  Y_feat <- cbind(
  #tsfeatures(interval,
  #           c("crossing_points")),
  #tsfeatures(interval,
 #            c("mean","var"), scale=FALSE, na.rm=TRUE)) 
    
    Y_feat <- cbind(
  tsfeatures(interval,
             c("acf_features","entropy","lumpiness",
               "flat_spots","crossing_points")),
  tsfeatures(interval, "std1st_der"),
  tsfeatures(interval,
             c("mean","var"), scale=FALSE, na.rm=TRUE),
  tsfeatures(interval,
             c("max_level_shift","max_var_shift"), trim=TRUE)) 


  #print(c(min(interval),max(interval)))
    #print(Y_feat$var)

  
  var=append(var, Y_feat$var)
  #av=append(av, Y_feat$max_level_shift)
 # cp=append(cp, Y_feat$flat_spots)
  
  

  timep=xinterval[abs(interval)>1400]
  peak=round((sum(diff(timep)>0.01)+1))
 

  

    if (Y_feat$var<thresh ){ #makes sure the switch is false if it is greater
      switch=FALSE
    }
    
    if( switch ==FALSE && signal[length(signal)]!=0){ #checks if we read a signal before
      
      if (mean(sc)>=0.09  && signalclass==FALSE){
        print("D")
        predicted=append(predicted, "D")
        signalclass=TRUE
        p=append(p,(max(peaks)))
        
      }
      if (mean(sc)<0.09  && signalclass==FALSE){
        print("S")
        predicted=append(predicted, "S")
        p=append(p,(max(peaks)))
        signalclass=TRUE
        print(max(peaks))
      }
       if (signalclass==TRUE){
        # print(signal)
       # print((sc))
        # print(diff(signal ))
         #print(max(diff(signal )))
        # print(Y_feat)
        ##spike=signal[abs(signal)>150]
       ## print(spike)
        #plot(signal, type="l")
         #turnsStats(interval)
         #print(sum(abs(interval)))
         
         
 # print(Y_feat)
       }
      
      }
      
    if (max_time < lower_interval + window_size + increment){#for last one if it ends by last window and needs to be classified

      if ( mean(sc)>=0.09 && signalclass==FALSE){#signal[1]<signal[length(signal)]
        print("D")
        predicted=append(predicted, "D")
        p=append(p,(max(peaks)))
        signalclass=TRUE
        print(max(peaks))
      }
      if (mean(sc)<0.09 && signalclass==FALSE){#signal[1]>signal[length(signal)] 
        print("S")
        predicted=append(predicted, "S")
        p=append(p,(max(peaks)))
        signalclass=TRUE
        print(sum(abs(interval)))
        print(max(peaks))
      }
      
      if (signalclass==TRUE){ #checking what the vector of values is 
       # print(signal)
      # print((sc))
       # print(Y_feat)
      ##  spike=signal[abs(signal)>150]
      ##  print(spike)
       # plot(signal, type="l")
       # print(sum(interval))
       # print(sum(abs(interval)))
        
 # print(Y_feat)
       }
    }
      
    
    if (Y_feat$var>=thresh && switch==FALSE){

    signal=c()
      peaks=c()
      switch=TRUE
      signalclass=FALSE
      sc=c()
    } 
    
    
    if (switch==TRUE){ #appends the mean to the signal 
      print("found!")
      
      signal=append(signal,Y_feat$mean )
      #sc=append(sc,interval[abs(interval)==max(abs(interval))])
      sc=append(sc, Y_feat$max_level_shift)
      plot(xinterval , interval)
      peaks=append(peaks,peak)
    }
    
    lower_interval = lower_interval + increment 
   ## end while
  }
  plot(var, type="l", lty=1, ylab="var")
  #plot(av, type="l", lty=1, ylab="average")
 # plot(cp, type="l", lty=1, ylab="zc")

#  matplot(cbind(var, av, cp), type="l", lty=1, ylab="statistics")
  #legend("topright", c("var", "mean", "zerocrossing"), lty=1, col=1:3)
  #print(predicted)
    return (c(predicted, p))
  
}## end function


```


```{r}


predacc=  function(filenames, predictions){
  accuracy=c()
  
  
  for (i in 1:length(filenames)){
    
    changes=stringdist(paste(predictions[[i]], collapse = ''),strsplit(filenames[i], "_")[[1]][1], method="lv")/nchar(strsplit(filenames[i], "_")[[1]][1])
    
    if (changes==0){
      changes=1
    }
    else if (changes==1){
      changes=0
    }
    
    accuracy=append(accuracy,changes)
  

  }
  return (accuracy)
  
}

```

```{r}
blink1 = "blinking-20210418T233857Z-001/blinking"
all_files_b1 <- list.files(blink1)


wave_file_b1 <- list()
predictions<- list()


for (i in all_files_b1) {
  wave_file_b1[[i]] <- readWave(file.path(blink1, i))
  

}

#snips out the sgnal 
wave_seq_short = list()

wave_file_b1


for (i in 1:(length(wave_file_b1))){
  print(i)
    
  timeSeq <- seq_len(length(wave_file_b1[[i]]@left))/wave_file_b1[[i]]@samp.rate 
  plot(timeSeq, wave_file_b1[[i]]@left, type = "l", ylab="Signal", xlab="Time(seconds)")


}
```


```{r}
blink2 = "double_blink"
all_files_b2 <- list.files(blink2)


wave_file_b2 <- list()
predictions2<- list()



for (i in all_files_b2) {
  wave_file_b2[[i]] <- readWave(file.path(blink2, i))
}



for (i in 1:(length(wave_file_b2))){
  print(i)
    
  timeSeq <- seq_len(length(wave_file_b2[[i]]@left))/wave_file_b2[[i]]@samp.rate 
  plot(timeSeq, wave_file_b2[[i]]@left, type = "l", ylab="Signal", xlab="Time(seconds)")

}


```
```{r}
blink2 = "double_blink"
all_files_b2 <- list.files(blink2)


wave_file_b2 <- list()
predictions2<- list()



for (i in all_files_b2) {
  wave_file_b2[[i]] <- readWave(file.path(blink2, i))
}



for (i in 1:(length(wave_file_b2))){
  print(i)
    
  timeSeq <- seq_len(length(wave_file_b2[[i]@left))/wave_file_b2[[i]]@samp.rate 
  df=data.frame(timeSeq, wav=wave_file_b2[[i]]@left)
  p=ggplot(data=df,aes(x=wav,y=timeSeq))+geom_line()+ylab("signal")+xlab("Time(seconds)")
  plotly::ggplotly(p)

}
```


```{r}
    
timeSeq <- seq_len(length(wave_file_b2[[1]]@left))/wave_file_b2[[1]]@samp.rate 
df=data.frame(timeSeq, wav=wave_file_b2[[1]]@left)
p=ggplot(data=df,aes(x=timeSeq,y=wav))+geom_line()+ylab("signal")+xlab("Time(seconds)")+geom_hline(yintercept=1600) +geom_hline(yintercept=-1600)
plotly::ggplotly(p)

```
```{r}
plot(seq_len(length(wave_file_b1[[1]]@left[210000:230000]))/20000,wave_file_b1[[1]]@left[210000:230000])


Y = wave_file_b1[[1]]@left[210000:230000] # all data is stored here
xtime = seq_len(length(wave_file_b1[[1]]@left[210000:230000]))/20000 #seq len
  
timep=xtime[abs(Y)>1500]
peaks=round((sum(diff(timep)>0.0001)+1))
peaks

  
#f=summary(c)

#f$info>700

```



```{r}
timeSeq <- seq_len(length(wave_file_b1[[1]]@left))/wave_file_b1[[1]]@samp.rate 
df=data.frame(timeSeq, wav=wave_file_b1[[1]]@left)
p=ggplot(data=df,aes(x=timeSeq,y=wav))+geom_line()+ylab("signal")+xlab("Time(seconds)")+geom_hline(yintercept=1400) +geom_hline(yintercept=-1400)
plotly::ggplotly(p)

```
```{r}
timeSeq <- seq_len(length(wave_file_b1[[5]]@left))/wave_file_b1[[5]]@samp.rate 
df=data.frame(timeSeq, wav=wave_file_b1[[5]]@left)
p=ggplot(data=df,aes(x=timeSeq,y=wav))+geom_line()+ylab("signal")+xlab("Time(seconds)")
plotly::ggplotly(p)

```



```{r}
dir_short ="blinking-20210418T233857Z-001/blinking" # "double_blink"
all_files_short <- list.files(dir_short)


wave_file_short <- list()
predictions<- list()



for (i in all_files_short) {
  wave_file_short[[i]] <- readWave(file.path(dir_short, i))
}

#snips out the sgnal 
wave_seq_short = list()

wave_file_short

#extrct signal returns us the index of all the points where there is a sequence --> predicted interval gives us the start and end points of the signal! 

for(i in 1:length(wave_file_short)){
  print(i)
  #print(wave_file_short[[i]])

  predictions[[i]]=streaming_classifier(wave_file_short, i)
  
}

#shortacc=(predacc(all_files_short,predictions))
#print(paste0("Overall Accuracy: " ,(mean(shortacc)*100), "%"))

```

```{r}
streaming_classifier(wave_file_b2, 1)

```
```{r}
streaming_classifier(wave_file_b1, 1)

```

```{r}
streaming_classifier(wave_file_b1, 5)


```

